### ISSUE TITLE
StringIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by lucevers** [Stratio/stratio-cassandra#34] opened 2015-06-04 07:26 UTC
I installed and tested test-users-create.cql -> oke works no problems.

But if I define my own fields I got:
StringIndexOutOfBoundsException String index out of range: 60

Question2:
  Do you need to use all the fields of your database in Lucene?

**Comment by adelapena** [comment] 2015-06-04 12:53
Regarding question 2, you don't need to index all the fields in the table, just those you need to search for.
About the exception, can you show your table schema and the failing index creation statement so that I can reproduce the issue?

**Comment by lucevers** [comment] 2015-06-05 11:43
Hi,

  Below all info:
  I also reduced the number of fields but this action produces the same error.
  Maybe the keyfield length is the problem?

cqlsh> CREATE KEYSPACE nurpr WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 2};


cqlsh:nurpr> CREATE TABLE nurprobtable (id TimeUUID PRIMARY KEY ,RNADITEID varchar , RNID varchar, RNACDNTRDCTVERSION varchar, PRFCRARTNTSTATUS varchar, RNASHARTCUSTNAME varchar, RNADITESSORTNAME varchar, T_EEEETRY_CODE varchar, RNTTTTTTSID varchar, RNAORIGTTTTTTTTTTID varchar, TREESS_GRPNUM varchar, GREESS_CURRENTSTATUS varchar, RNARRRRRRRTYPENAME varchar,RNATRCESSTYPENAME varchar,RNABACTUP varchar, RNATINEINFOKJGBER varchar,RNAGREID varchar,RNARTGDEPEID varchar, GPE_GRPNUM varchar,GPE_CURRENTSTATUS varchar, RNARETITEMID varchar,RNACPRTECTYPE varchar,RNACPETECSUBTYPE varchar, RNAMPEITEMREZDGR varchar, RNACPEDTEMGROUP varchar,RNASFFFTEMDDDDROUP varchar,RNACPEddddPdddUCTNUMBER varchar,stratio_col varchar);


cqlsh:nurpr> CREATE CUSTOM INDEX IF NOT EXISTS nurpr_index
         ... ON  nurpr.nurprobtable (stratio_col)
         ... USING 'org.apache.cassandra.db.index.stratio.RowIndex'
         ... WITH OPTIONS = {
         ...       'refresh_seconds':'1',
         ...       'num_cached_filters':'1',
         ...       'ram_buffer_mb':'64',
         ...       'max_merge_mb':'5',
         ...       'max_cached_mb':'30',
         ...       'schema':'{
         ...         default_analyzer:"org.apache.lucene.analysis.standard.StandardAnalyzer",
         ...         fields:{
         ...                 'id':{type:"uuid"},
         ...                 'RNADITEID':{type:"string"},
         ...                 'RNID':{type:"string"},
         ...                 'RNACDNTRDCTVERSION':{type:"string"},
         ...                 'PRFCRARTNTSTATUS':{type:"string"},
         ...                 'RNASHARTCUSTNAME':{type:"string"},
         ...                 'RNADITESSORTNAME':{type:"string"},
         ...                 'T_EEEETRY_CODE':{type:"string"},
         ...                 'RNTTTTTTSID':{type:"string"},
         ...                 'RNAORIGTTTTTTTTTTID':{type:"string"},
         ...                 'TREESS_GRPNUM':{type:"string"},
         ...                 'GREESS_CURRENTSTATUS':{type:"string"},
         ...                 'RNARRRRRRRTYPENAME':{type:"string"},
         ...                 'RNATRCESSTYPENAME':{type:"string"},
         ...                 'RNABACTUP':{type:"string"},
         ...                 'RNATINEINFOKJGBER':{type:"string"},
         ...                 'RNAGREID':{type:"string"},
         ...                 'RNARTGDEPEID':{type:"string"},
         ...                 'GPE_GRPNUM':{type:"string"},
         ...                 'GPE_CURRENTSTATUS':{type:"string"},
         ...                 'RNARETITEMID':{type:"string"},
         ...                 'RNACPRTECTYPE':{type:"string"},
         ...                 'RNACPETECSUBTYPE':{type:"string"},
         ...                 'RNAMPEITEMREZDGR':{type:"string"},
         ...                 'RNACPEDTEMGROUP':{type:"string"},
         ...                 'RNASFFFTEMDDDDROUP':{type:"string"},
         ...                 'RNACPEddddPdddUCTNUMBER':{type:"string"}
         ...                 }
         ... }'};
Bad Request: Failed parsing statement: [CREATE CUSTOM INDEX IF NOT EXISTS nurpr_index
ON  nurpr.nurprobtable (stratio_col)
USING 'org.apache.cassandra.db.index.stratio.RowIndex'
WITH OPTIONS = {
      'refresh_seconds':'1',
      'num_cached_filters':'1',
      'ram_buffer_mb':'64',
      'max_merge_mb':'5',
      'max_cached_mb':'30',
      'schema':'{
        default_analyzer:"org.apache.lucene.analysis.standard.StandardAnalyzer",
        fields:{
                'id':{type:"uuid"},
                'RNADITEID':{type:"string"},
                'RNID':{type:"string"},
                'RNACDNTRDCTVERSION':{type:"string"},
                'PRFCRARTNTSTATUS':{type:"string"},
                'RNASHARTCUSTNAME':{type:"string"},
                'RNADITESSORTNAME':{type:"string"},
                'T_EEEETRY_CODE':{type:"string"},
                'RNTTTTTTSID':{type:"string"},
                'RNAORIGTTTTTTTTTTID':{type:"string"},
                'TREESS_GRPNUM':{type:"string"},
                'GREESS_CURRENTSTATUS':{type:"string"},
                'RNARRRRRRRTYPENAME':{type:"string"},
                'RNATRCESSTYPENAME':{type:"string"},
                'RNABACTUP':{type:"string"},
                'RNATINEINFOKJGBER':{type:"string"},
                'RNAGREID':{type:"string"},
                'RNARTGDEPEID':{type:"string"},
                'GPE_GRPNUM':{type:"string"},
                'GPE_CURRENTSTATUS':{type:"string"},
                'RNARETITEMID':{type:"string"},
                'RNACPRTECTYPE':{type:"string"},
                'RNACPETECSUBTYPE':{type:"string"},
                'RNAMPEITEMREZDGR':{type:"string"},
                'RNACPEDTEMGROUP':{type:"string"},
                'RNASFFFTEMDDDDROUP':{type:"string"},
                'RNACPEddddPdddUCTNUMBER':{type:"string"}
                }
}'};] reason: StringIndexOutOfBoundsException String index out of range: 51

**Comment by adelapena** [comment] 2015-06-08 09:16
The single quote marks are not allowed inside the schema. You can use this index creation statement:
```
CREATE CUSTOM INDEX IF NOT EXISTS nurpr_index
 ON nurpr.nurprobtable (stratio_col)
 USING 'org.apache.cassandra.db.index.stratio.RowIndex'
 WITH OPTIONS = {
 'refresh_seconds':'1',
 'num_cached_filters':'1',
 'ram_buffer_mb':'64',
 'max_merge_mb':'5',
 'max_cached_mb':'30',
 'schema':'{
 default_analyzer:"org.apache.lucene.analysis.standard.StandardAnalyzer",
 fields:{
 id:{type:"uuid"},
 rnaditeid:{type:"string"},
 rnid:{type:"string"},
 rnacdntrdctversion:{type:"string"},
 prfcrartntstatus:{type:"string"},
 rnashartcustname:{type:"string"},
 rnaditessortname:{type:"string"},
 t_eeeetry_code:{type:"string"},
 rnttttttsid:{type:"string"},
 rnaorigttttttttttid:{type:"string"},
 treess_grpnum:{type:"string"},
 greess_currentstatus:{type:"string"},
 rnarrrrrrrtypename:{type:"string"},
 rnatrcesstypename:{type:"string"},
 rnabactup:{type:"string"},
 rnatineinfokjgber:{type:"string"},
 rnagreid:{type:"string"},
 rnartgdepeid:{type:"string"},
 gpe_grpnum:{type:"string"},
 gpe_currentstatus:{type:"string"},
 rnaretitemid:{type:"string"},
 rnacprtectype:{type:"string"},
 rnacpetecsubtype:{type:"string"},
 rnampeitemrezdgr:{type:"string"},
 rnacpedtemgroup:{type:"string"},
 rnasffftemddddroup:{type:"string"},
 rnacpeddddpddductnumber:{type:"string"}
 } }'}; 
``` 
Column names are lower case because CQL automatically lower cases the column names in your ``create table`` statement. If you want to preserve case sensitivity then you must double quote the column names at the table creation statement:
```
CREATE TABLE nurprobtable (
	id TimeUUID PRIMARY KEY ,
	"RNADITEID" varchar , 
	"RNID" varchar, 
	"RNACDNTRDCTVERSION" varchar, 
	"PRFCRARTNTSTATUS" varchar, 
	"RNASHARTCUSTNAME" varchar, 
	"RNADITESSORTNAME" varchar, 
	"T_EEEETRY_CODE" varchar, 
	"RNTTTTTTSID" varchar, 
	"RNAORIGTTTTTTTTTTID" varchar, 
	"TREESS_GRPNUM" varchar, 
	"GREESS_CURRENTSTATUS" varchar, 
	"RNARRRRRRRTYPENAME" varchar,
	"RNATRCESSTYPENAME" varchar,
	"RNABACTUP" varchar, 
	"RNATINEINFOKJGBER" varchar,
	"RNAGREID" varchar,
	"RNARTGDEPEID" varchar, 
	"GPE_GRPNUM" varchar,
	"GPE_CURRENTSTATUS" varchar, 
	"RNARETITEMID" varchar,
	"RNACPRTECTYPE" varchar,
	"RNACPETECSUBTYPE" varchar, 
	"RNAMPEITEMREZDGR" varchar, 
	"RNACPEDTEMGROUP" varchar,
	"RNASFFFTEMDDDDROUP" varchar,
	"RNACPEddddPdddUCTNUMBER" varchar,
	stratio_col varchar);
``` 
This way the index creation statement would be:
```
CREATE CUSTOM INDEX IF NOT EXISTS nurpr_index
 ON nurpr.nurprobtable (stratio_col)
 USING 'org.apache.cassandra.db.index.stratio.RowIndex'
 WITH OPTIONS = {
 'refresh_seconds':'1',
 'num_cached_filters':'1',
 'ram_buffer_mb':'64',
 'max_merge_mb':'5',
 'max_cached_mb':'30',
 'schema':'{
 default_analyzer:"org.apache.lucene.analysis.standard.StandardAnalyzer",
 fields:{
 id:{type:"uuid"},
 RNADITEID:{type:"string"},
 RNID:{type:"string"},
 RNACDNTRDCTVERSION:{type:"string"},
 PRFCRARTNTSTATUS:{type:"string"},
 RNASHARTCUSTNAME:{type:"string"},
 RNADITESSORTNAME:{type:"string"},
 T_EEEETRY_CODE:{type:"string"},
 RNTTTTTTSID:{type:"string"},
 RNAORIGTTTTTTTTTTID:{type:"string"},
 TREESS_GRPNUM:{type:"string"},
 GREESS_CURRENTSTATUS:{type:"string"},
 RNARRRRRRRTYPENAME:{type:"string"},
 RNATRCESSTYPENAME:{type:"string"},
 RNABACTUP:{type:"string"},
 RNATINEINFOKJGBER:{type:"string"},
 RNAGREID:{type:"string"},
 RNARTGDEPEID:{type:"string"},
 GPE_GRPNUM:{type:"string"},
 GPE_CURRENTSTATUS:{type:"string"},
 RNARETITEMID:{type:"string"},
 RNACPRTECTYPE:{type:"string"},
 RNACPETECSUBTYPE:{type:"string"},
 RNAMPEITEMREZDGR:{type:"string"},
 RNACPEDTEMGROUP:{type:"string"},
 RNASFFFTEMDDDDROUP:{type:"string"},
 RNACPEddddPdddUCTNUMBER:{type:"string"}
 } }'};
```

**Comment by lucevers** [comment] 2015-06-08 17:15
Thanks!
The single quote marks were used because I got an error on the "_" characters.

**Comment by adelapena** [comment] 2015-06-09 14:26
So, is it working? Can I close the issue?

**Comment by lucevers** [comment] 2015-06-10 14:54
Yes, everything is working now! You c

**Comment by lucevers** [comment] 2015-06-10 14:57
Yes, everything is working now. You can close the issue.
Small question if I drop the table I supose the Lucene index is also dropped?

**Comment by adelapena** [comment] 2015-06-10 15:20
Yes, if you delete the table then the index is also deleted.

**Closed by adelapena** 2015-06-10 15:20 UTC

**Comment by lucevers** [comment] 2015-06-11 17:30
Thanks for your help!
