### ISSUE TITLE
Problems indexing timeuuid columns

### ISSUE THREAD

**Issue by razvanz** [Stratio/stratio-cassandra#23] opened 2015-04-21 08:13 UTC
From `stratio-cassandra-2.1.3.0` and up I'm having issues with `timeuuid`  indexing. Is it a indexing issue? Should I use a different Analyzer?

The issue seems be raised when trying to deserialize `timeuuid`:

```
at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
```

My column family looks like: 
```
CREATE COLUMNFAMILY IF NOT EXISTS entity.enty
  (siloid timeuuid,
  entyid timeuuid,
  ...
  customindex text,
  PRIMARY KEY(siloid, entyid));
```

And the index: 
```
CREATE CUSTOM INDEX enty_filter
ON entity.enty (customindex)
USING 'org.apache.cassandra.db.index.stratio.RowIndex'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema' : '{
        default_analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer",
        fields : {
            siloid: {type: "uuid"},
            entyid: {type: "uuid"}
        }
    }'
};
```

Cassandra log:
```
INFO  07:15:46 Enqueuing flush of schema_columns: 2282 (0%) on-heap, 0 (0%) off-heap
INFO  07:15:46 Writing Memtable-schema_columns@1432822530(589 serialized bytes, 7 ops, 0%/0% of on/off-heap limit)
INFO  07:15:46 Completed flushing /Users/razvanz/Applications/stratio-cassandra-stratio-cassandra-2.1.4.0/bin/../data/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-71-Data.db (440 bytes) for commitlog position ReplayPosition(segmentId=1429600475177, position=383759)
INFO  07:15:46 Initializing index null
INFO  07:15:46 Initialized index entity.enty.enty_filter
INFO  07:15:46 Reloading index entity.enty.enty_filter
INFO  07:15:46 Submitting index build of enty_filter for data in 
INFO  07:15:46 Flushing index entity.enty.enty_filter
INFO  07:15:46 Enqueuing flush of enty: 0 (0%) on-heap, 0 (0%) off-heap
INFO  07:15:46 Committing
INFO  07:15:46 Column definitions for entity.enty changed, invalidating related prepared statements
INFO  07:15:46 Flushing SecondaryIndex RowIndex [index=enty_filter, keyspace=entity, table=enty, column=customindex
INFO  07:15:46 Flushing index entity.enty.enty_filter
INFO  07:15:46 Flushed index entity.enty.enty_filter
INFO  07:15:46 Committing
INFO  07:15:46 Index build of enty_filter complete
INFO  07:15:46 Flushed index entity.enty.enty_filter
INFO  07:21:34 Handshaking version with localhost/127.0.0.1
INFO  07:21:34 Handshaking version with localhost/127.0.0.1
WARN  07:37:40 Uncaught exception on thread Thread[SharedPool-Worker-6,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2164) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:82) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2161) ~[main/:na]
	... 4 common frames omitted
WARN  07:37:40 Uncaught exception on thread Thread[SharedPool-Worker-2,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2164) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:82) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2161) ~[main/:na]
	... 4 common frames omitted
WARN  07:40:00 Uncaught exception on thread Thread[SharedPool-Worker-4,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2164) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:82) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2161) ~[main/:na]
	... 4 common frames omitted
WARN  07:40:00 Uncaught exception on thread Thread[SharedPool-Worker-2,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2164) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:82) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2161) ~[main/:na]
	... 4 common frames omitted
WARN  07:41:31 Uncaught exception on thread Thread[SharedPool-Worker-7,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2164) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:82) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2161) ~[main/:na]
	... 4 common frames omitted
WARN  07:41:31 Uncaught exception on thread Thread[SharedPool-Worker-7,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2164) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:82) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2161) ~[main/:na]
	... 4 common frames omitted
WARN  07:45:29 Uncaught exception on thread Thread[SharedPool-Worker-5,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2164) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:82) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2161) ~[main/:na]
	... 4 common frames omitted
WARN  07:45:29 Uncaught exception on thread Thread[SharedPool-Worker-1,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2164) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:82) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2161) ~[main/:na]
	... 4 common frames omitted
```

**Comment by adelapena** [comment] 2015-04-21 13:56
I think that the problem is not related with the analyzer because UUID mapper always uses keyword analyzer. 

UUID mapper had some problems in 2.1.3.0, but I am not able to reproduce the issue with 2.1.3.1, 2.1.4.0 and the newly 2.1.4.1. I am using the following script:
```
CREATE KEYSPACE entity
         WITH REPLICATION = {'class' : 'SimpleStrategy',  'replication_factor': 1};
USE entity;
CONSISTENCY QUORUM;

CREATE COLUMNFAMILY IF NOT EXISTS entity.enty
  (siloid timeuuid,
  entyid timeuuid,
  other timeuuid,
  customindex text,
  PRIMARY KEY(siloid, entyid));


CREATE CUSTOM INDEX enty_filter
ON entity.enty (customindex)
USING 'org.apache.cassandra.db.index.stratio.RowIndex'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema' : '{
        default_analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer",
        fields : {
            siloid: {type: "uuid"},
            entyid: {type: "uuid"},
            other: {type: "uuid"}
        }
    }'
};

INSERT INTO entity.enty (siloid, entyid, other) VALUES (6219b550-e805-11e4-b85a-efbfad6da1e7 , 6219b551-e805-11e4-b85a-efbfad6da1e7,5fac85e0-e805-11e4-b85a-efbfad6da1e7);
INSERT INTO entity.enty (siloid, entyid, other) VALUES (5fac85e0-e805-11e4-b85a-efbfad6da1e7 , 5facacf0-e805-11e4-b85a-efbfad6da1e7, null);

SELECT * FROM entity.enty WHERE customindex = '{}';
SELECT * FROM entity.enty WHERE customindex = '{filter:{type:"match", field:"siloid", value:"6219b550-e805-11e4-b85a-efbfad6da1e7"}}';
SELECT * FROM entity.enty WHERE customindex = '{filter:{type:"match", field:"entyid", value:"6219b551-e805-11e4-b85a-efbfad6da1e7"}}';
SELECT * FROM entity.enty WHERE customindex = '{filter:{type:"match", field:"other", value:"5fac85e0-e805-11e4-b85a-efbfad6da1e7"}}';
SELECT * FROM entity.enty WHERE customindex = '{query:{type:"match", field:"siloid", value:"6219b550-e805-11e4-b85a-efbfad6da1e7"}}';
SELECT * FROM entity.enty WHERE customindex = '{query:{type:"match", field:"entyid", value:"6219b551-e805-11e4-b85a-efbfad6da1e7"}}';
SELECT * FROM entity.enty WHERE customindex = '{query:{type:"match", field:"other", value:"5fac85e0-e805-11e4-b85a-efbfad6da1e7"}}';
DELETE FROM entity.enty WHERE siloid=6219b550-e805-11e4-b85a-efbfad6da1e7 AND entyid=6219b551-e805-11e4-b85a-efbfad6da1e7;
SELECT * FROM entity.enty WHERE customindex = '{}';
```
Could you please try it with [stratio-cassandra-2.1.4.1](https://github.com/Stratio/stratio-cassandra/tree/stratio-cassandra-2.1.4.1)? Could you show me a row insertion leading to the index fail? Thanks!

**Comment by razvanz** [comment] 2015-04-21 14:42
I've tested [stratio-cassandra-2.1.4.1](https://github.com/Stratio/stratio-cassandra/tree/stratio-cassandra-2.1.4.1) and still get the same error.

Code used for testing:
```
CREATE KEYSPACE entity
         WITH REPLICATION = {'class' : 'SimpleStrategy',  'replication_factor': 1};
USE entity;

CONSISTENCY QUORUM;

CREATE COLUMNFAMILY IF NOT EXISTS entity.enty
  (container text,
  siloid timeuuid,
  entyid timeuuid,
  field1 timeuuid,
  customindex text,
  PRIMARY KEY((container, siloid), entyid, field1));


CREATE CUSTOM INDEX enty_filter
ON entity.enty (customindex)
USING 'org.apache.cassandra.db.index.stratio.RowIndex'
WITH OPTIONS = {
    'refresh_seconds': '1',
    'schema' : '{
        default_analyzer : "org.apache.lucene.analysis.standard.StandardAnalyzer",
        fields : {
            container: {type: "text"},
            siloid: {type: "uuid"},
            entyid: {type: "uuid"},
            field1: {type: "uuid"}
        }
    }'
};

INSERT INTO entity.enty (container, siloid, entyid, field1) VALUES ('a', 6219b550-e805-11e4-b85a-efbfad6da1e7 , 6219b551-e805-11e4-b85a-efbfad6da1e7, 5fac85e0-e805-11e4-b85a-efbfad6da1e7);

SELECT * FROM entity.enty
  WHERE
    container = 'a' AND
    siloid = 6219b550-e805-11e4-b85a-efbfad6da1e7 AND
    entyid = 6219b551-e805-11e4-b85a-efbfad6da1e7 AND
    customindex ='{
      "query": {
        "type":"boolean",
        "must":[{
          "type":"match",
          "field":"field1",
          "value":"5fac85e0-e805-11e4-b85a-efbfad6da1e7"
        }]
      }
    }';
```
And the error:
```
WARN  14:39:22 Uncaught exception on thread Thread[SharedPool-Worker-4,10,main]: {}
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2181) ~[main/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_71]
	at org.apache.cassandra.concurrent.AbstractTracingAwareExecutorService$FutureTask.run(AbstractTracingAwareExecutorService.java:164) ~[main/:na]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:105) [main/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.NullPointerException: null
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:32) ~[main/:na]
	at org.apache.cassandra.serializers.UUIDSerializer.deserialize(UUIDSerializer.java:26) ~[main/:na]
	at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.getComposedComponent(ClusteringKeyMapperColumns.java:111) ~[main/:na]
	at com.stratio.cassandra.index.service.ClusteringKeyMapperColumns.query(ClusteringKeyMapperColumns.java:150) ~[main/:na]
	at com.stratio.cassandra.index.service.RowMapperWide.query(RowMapperWide.java:187) ~[main/:na]
	at com.stratio.cassandra.index.service.RowService.search(RowService.java:244) ~[main/:na]
	at com.stratio.cassandra.index.RowIndexSearcher.search(RowIndexSearcher.java:88) ~[main/:na]
	at org.apache.cassandra.db.index.SecondaryIndexManager.search(SecondaryIndexManager.java:658) ~[main/:na]
	at org.apache.cassandra.db.ColumnFamilyStore.search(ColumnFamilyStore.java:2134) ~[main/:na]
	at org.apache.cassandra.db.PagedRangeCommand.executeLocally(PagedRangeCommand.java:113) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$LocalRangeSliceRunnable.runMayThrow(StorageProxy.java:1508) ~[main/:na]
	at org.apache.cassandra.service.StorageProxy$DroppableRunnable.run(StorageProxy.java:2178) ~[main/:na]
	... 4 common frames omitted
```

**Comment by adelapena** [comment] 2015-04-21 16:10
OK, there is a bug related to ClusteringKeyColumns class. It is a tricky optimization that is obsolete due to the last Lucene versions, so I have removed it. The changes are in [develop branch](https://github.com/Stratio/stratio-cassandra/tree/develop) and they will be merged into the next version very soon, together with Lucene 5.1.0. I hope it solve the issue. Thanks for reporting.

**Closed** 2015-06-09 14:57 UTC
