### ISSUE TITLE
How to query on map columns?

### ISSUE THREAD

**Issue by usopan** [Stratio/stratio-cassandra#35] opened 2015-06-05 09:02 UTC
I am trying to query on a map column assuming it to be like a text field. 
But none of the queries work. Queries work on other fields which are not map.
Also there is no example for map columns.

Is there a specific way  to query map columns?

**Comment by adelapena** [comment] 2015-06-08 16:00
You can query on map columns this way:
```
CREATE KEYSPACE demo WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1};

CREATE TABLE demo.items (
  id int PRIMARY KEY,
  properties map<text, text>,
  lucene text
);

CREATE CUSTOM INDEX demo_lucene ON  demo.items (lucene) USING 'com.stratio.cassandra.index.RowIndex' WITH OPTIONS = {
'refresh_seconds':'1', 
'schema':'{
 	default_analyzer:"Standard",
 	fields:{
 		id:{type:"integer"},
 		properties:{type:"string"}
 	}
 }'};

INSERT INTO demo.items (id,properties) VALUES (1,{'color':'red','rate':'18'});
INSERT INTO demo.items (id,properties) VALUES (2,{'color':'blue','rate':'19'});
INSERT INTO demo.items (id,properties) VALUES (3,{'color':'black','rate':'20'});

SELECT * FROM demo.items WHERE lucene='{filter:{type:"match",field:"properties.color", value:"red"}}';
```

**Comment by usopan** [comment] 2015-06-09 12:28
Is there a limitation on number of map entries?
coz it doesnt work for my schema object , when i test the script above it works.

**Comment by adelapena** [comment] 2015-06-09 14:51
I think the problem is not the number of columns. It could be related to the used analyzer. Can you please show me your index creation statement?

**Comment by usopan** [comment] 2015-06-10 06:16
CREATE CUSTOM INDEX IF NOT EXISTS cdr_index ON cdrlog2(lucene) USING 'com.stratio.cassandra.index.RowIndex' WITH OPTIONS={
	'refresh_seconds': '5',
	'ram_buffer_mb': '128',
	'max_merge_mb': '5',
	'max_cached_mb': '30',
	'indexing_threads': '4',
	'indexing_queues_size': '50',
	'schema': '{
		default_analyzer: "Standard",
		fields: {
			utctime: {
				type: "date",
				pattern: "yyyy/MM/dd HH:mm:ss"
			},
			cdr: {
				type: "string"
			}
		}
	}'
};

**Comment by usopan** [comment] 2015-06-10 07:16
Thanks for the clue  it worked with whitespace analyzer.

**Comment by adelapena** [comment] 2015-06-10 09:38
Great. Then I can close the issue.

**Closed by adelapena** 2015-06-10 09:38 UTC
